'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const lazy = path.resolve(__dirname, '..');
const toolkit = path.resolve(lazy, '..');

const glfw = fs.readFileSync(path.join(lazy, 'bindings', 'GLFW', 'GLFW.lsx'), 'utf8');
const gl = fs.readFileSync(path.join(lazy, 'bindings', 'OpenGL', 'OpenGL46.lsx'), 'utf8');
const al = fs.readFileSync(path.join(lazy, 'bindings', 'OpenAL', 'OpenAL.lsx'), 'utf8');
const threading = fs.readFileSync(path.join(lazy, 'bindings', 'System', 'Threading.lsx'), 'utf8');
const sockets = fs.readFileSync(path.join(lazy, 'bindings', 'Network', 'Sockets.lsx'), 'utf8');
const winsockRaw = fs.readFileSync(path.join(lazy, 'bindings', 'Network', 'WinSockRaw.lsx'), 'utf8');
const http = fs.readFileSync(path.join(lazy, 'bindings', 'Network', 'Http.lsx'), 'utf8');
const files = fs.readFileSync(path.join(lazy, 'bindings', 'System', 'File.lsx'), 'utf8');
const json = fs.readFileSync(path.join(lazy, 'bindings', 'Data', 'Json.lsx'), 'utf8');
const stbImage = fs.readFileSync(path.join(lazy, 'bindings', 'Graphics', 'STBImage.lsx'), 'utf8');
const image = fs.readFileSync(path.join(lazy, 'bindings', 'Graphics', 'Image.lsx'), 'utf8');
const texture = fs.readFileSync(path.join(lazy, 'bindings', 'Graphics', 'Texture2D.lsx'), 'utf8');
const textureUpload = fs.readFileSync(path.join(lazy, 'bindings', 'OpenGL', 'TextureUpload.lsx'), 'utf8');
const compiler = fs.readFileSync(path.join(lazy, 'compiler', 'lazyscriptex.js'), 'utf8');
const freeTypeRaw = fs.readFileSync(path.join(lazy, 'bindings', 'Text', 'FreeTypeRaw.lsx'), 'utf8');
const freeType = fs.readFileSync(path.join(lazy, 'bindings', 'Text', 'FreeType.lsx'), 'utf8');
const font = fs.readFileSync(path.join(lazy, 'bindings', 'Text', 'Font.lsx'), 'utf8');
const glmRaw = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'GLMRaw.lsx'), 'utf8');
const glm = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'GLM.lsx'), 'utf8');
const cameraMath = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'Camera.lsx'), 'utf8');
const glmOpenGL = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'OpenGL.lsx'), 'utf8');
assert(glfw.includes('export extern "LSXGameKit.dll" fn glfwSetWindowIcon'), 'raw GLFW window icon binding missing');
assert(glfw.includes('export fn setWindowIconRGBA'), 'typed GLFW RGBA icon helper missing');
assert(glfw.includes('export const FramebufferSize'), 'typed framebuffer size object missing');
assert(gl.includes('export fn createBuffer()'), 'typed OpenGL buffer helper missing');
assert(gl.includes('export fn getInteger(pname)'), 'typed OpenGL scalar query missing');
assert(al.includes('export fn createSource()'), 'typed OpenAL source helper missing');
assert(threading.includes('thread.start(entry,context)'), 'native LSX thread start wrapper missing');
assert(threading.includes('export const ConditionVariable'), 'condition-variable support missing');
assert(threading.includes('atomic.i64_increment(self)'), 'compiler-emitted native 64-bit atomics missing');
assert(!threading.includes('extern "KERNEL32.dll" fn Interlocked'), 'Interlocked macros must not be imported as DLL entry points');
assert(winsockRaw.includes('export extern "WS2_32.dll" fn socket'), 'raw WinSock2 binding missing');
assert(sockets.includes('use "WinSockRaw.lsx" as Raw'), 'high-level sockets are not isolated from raw WinSock names');
assert(sockets.includes('udp_bind = fn'), 'UDP bind API missing');
assert(sockets.includes('receive_exact = fn'), 'TCP exact receive helper missing');
assert(http.includes('extern "WINHTTP.dll" fn WinHttpOpen'), 'WinHTTP binding missing');
assert(http.includes('post_text = fn'), 'HTTP text/JSON POST helper missing');
assert(files.includes('export fn read_bytes'), 'native file read API missing');
assert(files.includes('export fn write_text'), 'native file text write API missing');
assert(json.includes('export const Document'), 'native JSON document missing');
assert(json.includes('export fn parse_text'), 'native JSON parser missing');
assert(stbImage.includes('extern "stb_image.dll" fn stbi_load'), 'direct stb_image decoder binding missing');
assert(stbImage.includes('stbi_image_free'), 'stb_image owned pixel cleanup missing');
assert(stbImage.includes('rgba32 = fn(index:i64)'), 'typed stb_image RGBA pixel accessor missing');
assert(image.includes('use "STBImage.lsx" as STBImage'), 'Image facade is not backed by stb_image');
assert(texture.includes('export fn load_ui'), 'OpenGL Texture2D helper missing');
assert(texture.includes('export fn load_flipped'), 'explicit flipped Texture2D loader missing');
assert(texture.includes('export fn load_ui_flipped'), 'explicit flipped UI Texture2D loader missing');
assert(texture.includes('return load_ex(path,true,true,false)'), 'default Texture2D loader must preserve stb_image row order');
assert(texture.includes('return load_ex(path,false,false,false)'), 'UI Texture2D loader must preserve stb_image row order');
assert(texture.includes('pixels.resize_bytes(byteCount)'), 'Texture2D is not allocating an inferred byte buffer');
assert(texture.includes('pixels.copy_bytes_from_ptr(image.pixels(),byteCount)'), 'Texture2D is not using the compiler byte-buffer foreign-memory copy API');
assert(!texture.includes('image.rgba32(index)'), 'Texture2D must not rebuild the decoded image through a per-pixel accessor loop');
assert(texture.includes('GL.glTexImage2D'), 'Texture2D is not using the standard OpenGL upload path from example 04');
assert(!texture.includes('TextureUpload.rgba8'), 'Texture2D must not route RGBA images through the FreeType ABI helper');
assert(!texture.includes('extern "msvcrt.dll" fn memcpy'), 'Texture2D must use the compiler table copy API instead of declaring memcpy itself');
assert(compiler.includes("builtin('table.copy_from_ptr'"), 'compiler table foreign-memory copy builtin missing');
assert(compiler.includes("const byteTableMethods = new Set(['byte_data','copy_bytes_from_ptr','reserve_bytes','resize_bytes'])"), 'annotation-free byte-buffer inference methods missing');
assert(compiler.includes('Math.min(6'), 'O6 optimizer level is not enabled');
assert(compiler.includes("a.label('__lsx_table_copy_from_ptr')"), 'compiler table foreign-memory copy runtime missing');
assert(!texture.includes('glGetTexLevelParameteriv'), 'Texture2D must not perform the crashing post-upload texture query');
assert(textureUpload.includes('extern "LSXGLABI.dll" fn lsxGlTexImage2DCall'), 'exact glTexImage2D ABI bridge binding missing');
assert(textureUpload.includes('GL.GL_RGBA8'), 'RGBA8 texture upload path missing');
assert(textureUpload.includes('GL.GL_RED'), 'single-channel font atlas upload path missing');
assert(compiler.includes("['lsxglabi.dll', ['@LazyScript/native/LSXGLABI.dll']]"), 'LSXGLABI runtime staging rule missing');
assert(freeTypeRaw.includes('extern "libfreetype.dll" fn FT_Init_FreeType'), 'raw FreeType API binding missing');
assert(freeType.includes('_lsxFTLoadGlyph'), 'typed FreeType glyph binding missing');
assert(font.includes('export fn create_ascii_atlas'), 'SDF font atlas API missing');
assert(font.includes('export fn build_text'), 'batched text mesh API missing');
const appendTextStart = font.indexOf('export fn append_text_instances');
const appendTextEnd = font.indexOf('export fn upload_atlas', appendTextStart);
const appendTextSource = font.slice(appendTextStart, appendTextEnd);
assert(appendTextSource.includes('output.push(x1 - x0)') && appendTextSource.includes('output.push(y1 - y0)'), 'instanced SDF glyph records must store width/height, not absolute x1/y1 coordinates');
assert(font.includes('result.pixels.resize_bytes(result.width * result.height)'), 'SDF atlas is not allocating an inferred byte buffer');
assert(font.includes('result.pixels.byte_data()'), 'SDF atlas is not exposing its byte buffer to FreeType');
assert(glmRaw.includes('extern "LSXMath.dll" fn _lsxGLMMat4PerspectiveRHNO'), 'raw GLM projection bridge missing');
assert(glm.includes('export const Vec2'), 'wrapped GLM Vec2 missing');
assert(glm.includes('export const Vec3'), 'wrapped GLM Vec3 missing');
assert(glm.includes('export const Vec4'), 'wrapped GLM Vec4 missing');
assert(glm.includes('export const Mat2'), 'wrapped GLM Mat2 missing');
assert(glm.includes('export const Mat3'), 'wrapped GLM Mat3 missing');
assert(glm.includes('export const Mat4'), 'wrapped GLM Mat4 missing');
assert(glm.includes('export const Quat'), 'wrapped GLM quaternion missing');
assert(glm.includes('export const DualQuat'), 'wrapped GLM dual quaternion missing');
assert(glm.includes('export fn decompose'), 'wrapped GLM decomposition missing');
assert(glm.includes('export fn pick_matrix'), 'wrapped GLM pick matrix missing');
assert(glm.includes('faceforward = fn'), 'wrapped GLM faceforward operations missing');
assert(glm.includes('rotate_vec4 = fn'), 'wrapped quaternion Vec4 rotation missing');
assert(!glm.includes('-> ptr'), 'public GLM wrapper must not expose native pointers');
assert(!glm.includes('export extern'), 'public GLM wrapper must not expose raw extern declarations');
assert(cameraMath.includes('export const Camera'), 'typed GLM camera object missing');
assert(cameraMath.includes('view_projection = fn'), 'camera view-projection helper missing');
assert(glmOpenGL.includes('export fn uniform_mat4'), 'GLM OpenGL matrix upload helper missing');
assert(compiler.includes("['lsxmath.dll', ['@LazyScript/native/LSXMath.dll']]"), 'LSXMath runtime staging rule missing');
assert(fs.existsSync(path.join(lazy, 'native', 'stb_image.dll')), 'stb_image native runtime missing');
assert(fs.existsSync(path.join(lazy, 'native', 'libfreetype.dll')), 'FreeType native runtime missing');
assert(fs.existsSync(path.join(lazy, 'native', 'LSXFreeType.dll')), 'FreeType LSX ABI bridge missing');
assert(fs.existsSync(path.join(lazy, 'native', 'LSXGLABI.dll')), 'exact OpenGL ABI bridge missing');
assert(fs.existsSync(path.join(lazy, 'native', 'LSXMath.dll')), 'GLM native runtime missing');

const fileExample = fs.readFileSync(path.join(toolkit, 'Projects', '21_file_io', 'main.lsx'), 'utf8');
assert(!fileExample.includes('"build/file_io_test.txt"'), 'file example must not write into build/build when run from the build directory');
assert(fileExample.includes('console.wait()'), 'file example must keep its console visible');
assert(fileExample.includes('Log.open_default()'), 'file example must leave persistent stage logs');
const jsonExample = fs.readFileSync(path.join(toolkit, 'Projects', '22_json', 'main.lsx'), 'utf8');
assert(jsonExample.includes('Log.open_default()'), 'JSON example must leave persistent stage logs');
assert(jsonExample.includes('console.wait()'), 'JSON example must keep its console visible');
assert(json.includes('source = {}'), 'JSON document must own inferred native source storage');

const examples = fs.readdirSync(path.join(toolkit, 'Projects'), { withFileTypes: true })
  .filter(e => e.isDirectory()).map(e => path.join(toolkit, 'Projects', e.name, 'main.lsx')).filter(fs.existsSync);
for (const file of examples) {
  const source = fs.readFileSync(file, 'utf8');
  assert(!/\bmemory\./.test(source), `${file} still exposes raw memory operations in project code`);
}

const allLsxFiles = [];
function collectLsx(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'build') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) collectLsx(full);
    else if (entry.isFile() && entry.name.endsWith('.lsx')) allLsxFiles.push(full);
  }
}
collectLsx(lazy);
collectLsx(path.join(toolkit, 'Projects'));
for (const file of allLsxFiles) {
  const source = fs.readFileSync(file, 'utf8');
  assert(!/\btable\s*</.test(source), `${file} still exposes typed collection syntax`);
}

const imageExample = fs.readFileSync(path.join(toolkit, 'Projects', '24_image_loading', 'main.lsx'), 'utf8');
assert(imageExample.includes('LSG.load_ui_texture("assets/loaded_texture.png")'), 'image example is not using the beginner-facing LSG texture API');
assert(imageExample.includes('texture.bind(0)'), 'image example is not binding the decoded texture through LSG');
assert(imageExample.includes('LSG.mesh_mode(vertices,Image.vertex_layout,LSG.TRIANGLE_STRIP)'), 'image example is not using the shader-owned vertex layout through LSG');
assert(imageExample.includes('-0.8,-0.8, 0.0,1.0'), 'image example bottom UV no longer matches example 04');
assert(imageExample.includes('-0.8, 0.8, 0.0,0.0'), 'image example top UV no longer matches example 04');
assert(!imageExample.includes('TextureUpload'), 'image example must not use the FreeType texture-upload helper');
assert(imageExample.includes('Log.open_default()'), 'image example must leave persistent stage logs');
assert(imageExample.includes('First image frame rendered'), 'image example must log its first successful rendered frame');
const glmExample = fs.readFileSync(path.join(toolkit, 'Projects', '27_glm_camera', 'main.lsx'), 'utf8');
assert(glmExample.includes('use "@LazyScript/bindings/Math/GLM.lsx" as GLM'), 'GLM camera example does not use the typed wrapper');
assert(glmExample.includes('use "@LazyScript/bindings/Math/Camera.lsx" as Camera'), 'GLM camera example does not use the typed camera');
assert(glmExample.includes('GLM.trs(position,rotation,scale)'), 'GLM camera example does not use wrapped TRS');
assert(glmExample.includes('shader.matrix4("model",model)'), 'GLM camera example does not upload typed matrices through LSSL');
const triangle = fs.readFileSync(path.join(toolkit, 'Projects', '02_opengl_triangle', 'main.lsx'), 'utf8');
assert(triangle.includes('local vertices = {'), 'triangle does not use packed positional LSX object data');
assert(triangle.includes('LSG.mesh(vertices,Triangle.vertex_layout)'), 'triangle does not use the LSSL-generated vertex layout');
const lsgSource = fs.readFileSync(path.join(lazy, 'LSG.lsx'), 'utf8');
assert(!lsgSource.includes('framebuffer:GLFW.FramebufferSize'), 'LSG Window still stores the temporary framebuffer helper that can leave a zero viewport');
assert(lsgSource.includes('GLFW.glfwGetFramebufferSize(self.handle,self,memory.ptr(self,4))'), 'LSG Window does not write framebuffer dimensions directly into stable fields');
assert(!lsgSource.includes('fn add_attribute('), 'LSG mesh setup still routes vertex attributes through the unstable extra wrapper');
assert(lsgSource.includes('fn apply_layout(layout,stride)'), 'LSG does not decode the scalar LSSL vertex layout');
assert(lsgSource.includes('GL.glVertexAttribPointer(attribute,size,GL.GL_FLOAT,GL.GL_FALSE,stride,offset)'), 'LSG mesh setup is not using the direct vertex attribute call shape');
assert(!lsgSource.includes('layout[index]'), 'LSG still indexes a cross-module temporary layout table');
const lsslSource = fs.readFileSync(path.join(lazy, 'LSSL.lsx'), 'utf8');
assert(lsslSource.includes('GL.glCreateShader(kind)'), 'LSSL does not own the shader stage compile path');
assert(lsslSource.includes('GL.shaderInfoLog(shader)'), 'LSSL does not preserve the graphics driver shader log');
assert(lsslSource.includes('GL.programInfoLog(program)'), 'LSSL does not preserve the graphics driver program link log');
const audio = fs.readFileSync(path.join(toolkit, 'Projects', '08_openal_generated_tone', 'main.lsx'), 'utf8');
const samplesBinding = fs.readFileSync(path.join(lazy, 'bindings', 'OpenAL', 'Samples.lsx'), 'utf8');
assert(audio.includes('Samples.triangle('), 'generated audio does not use the beginner-safe PCM helper');
assert(audio.includes('pcm.upload(buffer)'), 'generated audio does not upload through the PCM helper');
assert(!audio.includes('memory.'), 'generated audio still exposes raw memory operations');
assert(samplesBinding.includes('bytes.resize_bytes(sample_count * 2)'), 'PCM helper does not allocate packed 16-bit sample bytes');
assert(samplesBinding.includes('memory.write_u16'), 'PCM helper does not write exact PCM16 samples');
assert(samplesBinding.includes('fn make_triangle(frequency:f32,seconds:f32,volume:f32,fade:bool)'), 'PCM helper does not anchor its internal numeric values as floating point');
assert(samplesBinding.includes('export fn triangle(frequency,seconds,volume)'), 'public generated tone API must remain inference-only');
assert(audio.includes('Samples.triangle(220.0,1.0,0.15)'), 'generated tone example does not preserve frequency, duration, and fractional volume as floats');
assert(!audio.includes('table<'), 'generated audio still exposes a typed collection annotation');
const wavProject = path.join(toolkit, 'Projects', '09_openal_wav_playback');
const wavConfig = JSON.parse(fs.readFileSync(path.join(wavProject, 'lazyscriptex.json'), 'utf8'));
assert(wavConfig.runtimeFiles.includes('tone.wav'), 'WAV playback project does not copy tone.wav beside the executable');
assert(fs.existsSync(path.join(wavProject, 'tone.wav')), 'WAV playback source asset is missing');
const efxAudio = fs.readFileSync(path.join(toolkit, 'Projects', '10_openal_efx_reverb', 'main.lsx'), 'utf8');
assert(efxAudio.includes('Samples.fading_triangle(196.0,0.7,0.12)'), 'EFX example does not use the corrected floating-point generated tone');
assert(efxAudio.includes('AL.alGetError() ~= AL.AL_NO_ERROR'), 'EFX example does not report an OpenAL effect setup failure');
const compilerApi = require('./lazyscriptex.js');
const audioCheck = compilerApi.checkFile(path.join(toolkit, 'Projects', '08_openal_generated_tone', 'main.lsx'), { LazyScript: lazy }, { allowDeferredLocalMethods: true });
const sampleModule = audioCheck.program.moduleOrder.find(module => module.filePath.endsWith(path.join('OpenAL', 'Samples.lsx')));
const triangleFunction = sampleModule.functions.get('triangle');
assert.deepStrictEqual(triangleFunction.params.map(param => param.type), ['f32','f32','f32'], 'generated tone public parameters did not infer as floating point');
const proceduralTexture = fs.readFileSync(path.join(toolkit, 'Projects', '04_texture_checkerboard', 'main.lsx'), 'utf8');
const generatedIcon = fs.readFileSync(path.join(toolkit, 'Projects', '13_window_icon_rgba', 'main.lsx'), 'utf8');
assert(proceduralTexture.includes('LSG.pixel_image(64,64)'), 'procedural texture does not use packed PixelImage storage');
assert(proceduralTexture.includes('LSG.texture_from_pixels(pixels)'), 'procedural texture does not upload through the safe pixel path');
assert(generatedIcon.includes('LSG.pixel_image(32,32)'), 'generated icon does not use packed PixelImage storage');
assert(generatedIcon.includes('window.set_icon(icon)'), 'generated icon does not use the PixelImage window API');
assert(lsgSource.includes('bytes.resize_bytes(width * height * 4)'), 'LSG PixelImage does not allocate packed RGBA8 bytes');
assert(lsgSource.includes('memory.write_u8(data,offset'), 'LSG PixelImage does not write exact RGBA channels');
assert(!fs.existsSync(path.join(lazy, 'bindings', 'Platform', 'WICImage.lsx')), 'WIC should not be active');
const api = JSON.parse(fs.readFileSync(path.join(lazy, 'api', 'api-data.json'), 'utf8'));
assert(api.stats.total >= 9000, 'offline HTML API is incomplete');
const extensionPackage = JSON.parse(fs.readFileSync(path.join(lazy, 'extension', 'package.json'), 'utf8'));
const installerSource = fs.readFileSync(path.join(toolkit, 'INSTALL_VSCODE_EXTENSION.bat'), 'utf8');
const packagedVsix = 'LazyScriptEX-Native-GameKit.vsix';
assert(fs.existsSync(path.join(toolkit, packagedVsix)), 'VS Code VSIX missing');
assert(installerSource.includes(packagedVsix), 'VS Code extension installer does not reference the packaged VSIX');
assert(fs.existsSync(path.join(toolkit, 'INSTALL_VSCODE_EXTENSION.bat')), 'VS Code extension installer missing');
assert(api.stats.modules['System/Threading'] > 0, 'threading API is missing from offline docs');
assert(api.stats.modules['Network/Sockets'] > 0, 'socket API is missing from offline docs');
assert(api.stats.modules['Network/Http'] > 0, 'HTTP API is missing from offline docs');
assert(api.stats.modules['System/File'] > 0, 'file API is missing from offline docs');
assert(api.stats.modules['Data/Json'] > 0, 'JSON API is missing from offline docs');
assert(api.stats.modules['Graphics/STBImage'] > 0, 'stb_image API is missing from offline docs');
assert(api.stats.modules['Graphics/Image'] > 0, 'image API is missing from offline docs');
assert(api.stats.modules['Graphics/Texture2D'] > 0, 'texture API is missing from offline docs');
assert(api.stats.modules['OpenGL/TextureUpload'] > 0, 'exact texture upload API is missing from offline docs');
assert(api.stats.modules['Text/FreeTypeRaw'] > 0, 'raw FreeType API is missing from offline docs');
assert(api.stats.modules['Text/FreeType'] > 0, 'typed FreeType API is missing from offline docs');
assert(api.stats.modules['Text/Font'] > 0, 'font API is missing from offline docs');
assert(api.stats.modules['Math/GLM'] > 0, 'typed GLM API is missing from offline docs');
assert(api.stats.modules['Math/GLMRaw'] > 0, 'raw GLM bridge API is missing from offline docs');
assert(api.stats.modules['Math/Camera'] > 0, 'camera math API is missing from offline docs');
assert(api.stats.modules['Math/OpenGL'] > 0, 'GLM OpenGL API is missing from offline docs');
assert(api.stats.modules['Language/Objects'] >= 5, 'constructors or ordinary object API entries are missing');
assert(api.entries.some(entry => entry.module === 'Language/Objects' && entry.name === 'constructor'), 'object constructor API is missing');
assert(api.entries.some(entry => entry.module === 'Language/Static objects' && entry.name === 'static constructor'), 'static constructor API is missing');
assert(api.stats.modules['LazyUI/LSHTML elements'] >= 250, 'complete LSHTML element API is missing');
assert(api.stats.modules['LazyUI/LSHTML attributes'] >= 50, 'complete LSHTML attribute API is missing');
assert(api.stats.modules['LazyUI/LSCSS properties'] >= 100, 'complete LSCSS property API is missing');
assert(api.entries.some(entry => entry.module === 'UI/LazyUI' && entry.owner === 'Document' && entry.name === 'find'), 'Document.find is missing from the API');
assert(api.entries.some(entry => entry.module === 'UI/LazyUI' && entry.owner === 'Element' && entry.name === 'add_event_listener'), 'Element.add_event_listener is missing from the API');
const apiApp = fs.readFileSync(path.join(lazy, 'api', 'app.js'), 'utf8');
assert(apiApp.includes("module.startsWith('UI/') || module.startsWith('LazyUI/')"), 'LSHTML/LSCSS API modules are not grouped under User interface');
assert(api.stats.kinds.method > 150, 'object methods are missing from rich API metadata');
assert(api.entries.some((entry) => entry.description && entry.description.length > 10), 'API descriptions are missing');
console.log('GLM math and cameras, annotation-free inferred collections, strings, files, JSON, direct stb_image, OpenGL textures, direct FreeType SDF fonts, compiler-emitted atomics, real threading, automatic runtime staging, sockets, HTTP, native LSHTML/LSCSS LazyUI, and VS Code package checks passed.');
