'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const lazy = path.resolve(__dirname, '..');
const toolkit = path.resolve(lazy, '..');

const glfw = fs.readFileSync(path.join(lazy, 'bindings', 'GLFW', 'GLFW.lsx'), 'utf8');
const gl = fs.readFileSync(path.join(lazy, 'bindings', 'OpenGL', 'OpenGL46.lsx'), 'utf8');
const al = fs.readFileSync(path.join(lazy, 'bindings', 'OpenAL', 'OpenAL.lsx'), 'utf8');
const threading = fs.readFileSync(path.join(lazy, 'bindings', 'System', 'Threading.lsx'), 'utf8');
const sockets = fs.readFileSync(path.join(lazy, 'bindings', 'Network', 'Sockets.lsx'), 'utf8');
const winsockRaw = fs.readFileSync(path.join(lazy, 'bindings', 'Network', 'WinSockRaw.lsx'), 'utf8');
const http = fs.readFileSync(path.join(lazy, 'bindings', 'Network', 'Http.lsx'), 'utf8');
const files = fs.readFileSync(path.join(lazy, 'bindings', 'System', 'File.lsx'), 'utf8');
const json = fs.readFileSync(path.join(lazy, 'bindings', 'Data', 'Json.lsx'), 'utf8');
const stbImage = fs.readFileSync(path.join(lazy, 'bindings', 'Graphics', 'STBImage.lsx'), 'utf8');
const image = fs.readFileSync(path.join(lazy, 'bindings', 'Graphics', 'Image.lsx'), 'utf8');
const texture = fs.readFileSync(path.join(lazy, 'bindings', 'Graphics', 'Texture2D.lsx'), 'utf8');
const textureUpload = fs.readFileSync(path.join(lazy, 'bindings', 'OpenGL', 'TextureUpload.lsx'), 'utf8');
const compiler = fs.readFileSync(path.join(lazy, 'compiler', 'lazyscriptex.js'), 'utf8');
const freeTypeRaw = fs.readFileSync(path.join(lazy, 'bindings', 'Text', 'FreeTypeRaw.lsx'), 'utf8');
const freeType = fs.readFileSync(path.join(lazy, 'bindings', 'Text', 'FreeType.lsx'), 'utf8');
const font = fs.readFileSync(path.join(lazy, 'bindings', 'Text', 'Font.lsx'), 'utf8');
const glmRaw = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'GLMRaw.lsx'), 'utf8');
const glm = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'GLM.lsx'), 'utf8');
const cameraMath = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'Camera.lsx'), 'utf8');
const glmOpenGL = fs.readFileSync(path.join(lazy, 'bindings', 'Math', 'OpenGL.lsx'), 'utf8');
assert(glfw.includes('export extern "LSXGameKit.dll" fn glfwSetWindowIcon'), 'raw GLFW window icon binding missing');
assert(glfw.includes('export fn setWindowIconRGBA'), 'typed GLFW RGBA icon helper missing');
assert(glfw.includes('export const FramebufferSize'), 'typed framebuffer size object missing');
assert(gl.includes('export fn createBuffer()'), 'typed OpenGL buffer helper missing');
assert(gl.includes('export fn getInteger(pname)'), 'typed OpenGL scalar query missing');
assert(al.includes('export fn createSource()'), 'typed OpenAL source helper missing');
assert(threading.includes('thread.start(entry,context)'), 'native LSX thread start wrapper missing');
assert(threading.includes('export const ConditionVariable'), 'condition-variable support missing');
assert(threading.includes('atomic.i64_increment(self)'), 'compiler-emitted native 64-bit atomics missing');
assert(!threading.includes('extern "KERNEL32.dll" fn Interlocked'), 'Interlocked macros must not be imported as DLL entry points');
assert(winsockRaw.includes('export extern "WS2_32.dll" fn socket'), 'raw WinSock2 binding missing');
assert(sockets.includes('use "WinSockRaw.lsx" as Raw'), 'high-level sockets are not isolated from raw WinSock names');
assert(sockets.includes('udp_bind = fn'), 'UDP bind API missing');
assert(sockets.includes('receive_exact = fn'), 'TCP exact receive helper missing');
assert(http.includes('extern "WINHTTP.dll" fn WinHttpOpen'), 'WinHTTP binding missing');
assert(http.includes('post_text = fn'), 'HTTP text/JSON POST helper missing');
assert(files.includes('export fn read_bytes'), 'native file read API missing');
assert(files.includes('export fn write_text'), 'native file text write API missing');
assert(json.includes('export const Document'), 'native JSON document missing');
assert(json.includes('export fn parse_text'), 'native JSON parser missing');
assert(stbImage.includes('extern "stb_image.dll" fn stbi_load'), 'direct stb_image decoder binding missing');
assert(stbImage.includes('stbi_image_free'), 'stb_image owned pixel cleanup missing');
assert(stbImage.includes('rgba32 = fn(index:i64)'), 'typed stb_image RGBA pixel accessor missing');
assert(image.includes('use "STBImage.lsx" as STBImage'), 'Image facade is not backed by stb_image');
assert(texture.includes('export fn load_ui'), 'OpenGL Texture2D helper missing');
assert(texture.includes('export fn load_flipped'), 'explicit flipped Texture2D loader missing');
assert(texture.includes('export fn load_ui_flipped'), 'explicit flipped UI Texture2D loader missing');
assert(texture.includes('return load_ex(path,true,true,false)'), 'default Texture2D loader must preserve stb_image row order');
assert(texture.includes('return load_ex(path,false,false,false)'), 'UI Texture2D loader must preserve stb_image row order');
assert(texture.includes('pixels.resize_bytes(byteCount)'), 'Texture2D is not allocating an inferred byte buffer');
assert(texture.includes('pixels.copy_bytes_from_ptr(image.pixels(),byteCount)'), 'Texture2D is not using the compiler byte-buffer foreign-memory copy API');
assert(!texture.includes('image.rgba32(index)'), 'Texture2D must not rebuild the decoded image through a per-pixel accessor loop');
assert(texture.includes('GL.glTexImage2D'), 'Texture2D is not using the standard OpenGL upload path from example 04');
assert(!texture.includes('TextureUpload.rgba8'), 'Texture2D must not route RGBA images through the FreeType ABI helper');
assert(!texture.includes('extern "msvcrt.dll" fn memcpy'), 'Texture2D must use the compiler table copy API instead of declaring memcpy itself');
assert(compiler.includes("builtin('table.copy_from_ptr'"), 'compiler table foreign-memory copy builtin missing');
assert(compiler.includes("const byteTableMethods = new Set(['byte_data','copy_bytes_from_ptr','reserve_bytes','resize_bytes'])"), 'annotation-free byte-buffer inference methods missing');
assert(compiler.includes('Math.min(6'), 'O6 optimizer level is not enabled');
assert(compiler.includes("a.label('__lsx_table_copy_from_ptr')"), 'compiler table foreign-memory copy runtime missing');
assert(!texture.includes('glGetTexLevelParameteriv'), 'Texture2D must not perform the crashing post-upload texture query');
assert(textureUpload.includes('extern "LSXGLABI.dll" fn lsxGlTexImage2DCall'), 'exact glTexImage2D ABI bridge binding missing');
assert(textureUpload.includes('GL.GL_RGBA8'), 'RGBA8 texture upload path missing');
assert(textureUpload.includes('GL.GL_RED'), 'single-channel font atlas upload path missing');
assert(compiler.includes("['lsxglabi.dll', ['@LazyScript/native/LSXGLABI.dll']]"), 'LSXGLABI runtime staging rule missing');
assert(freeTypeRaw.includes('extern "libfreetype.dll" fn FT_Init_FreeType'), 'raw FreeType API binding missing');
assert(freeType.includes('_lsxFTLoadGlyph'), 'typed FreeType glyph binding missing');
assert(font.includes('export fn create_ascii_atlas'), 'SDF font atlas API missing');
assert(font.includes('export fn build_text'), 'batched text mesh API missing');
const appendTextStart = font.indexOf('export fn append_text_instances');
const appendTextEnd = font.indexOf('export fn upload_atlas', appendTextStart);
const appendTextSource = font.slice(appendTextStart, appendTextEnd);
assert(appendTextSource.includes('output.push(x1 - x0)') && appendTextSource.includes('output.push(y1 - y0)'), 'instanced SDF glyph records must store width/height, not absolute x1/y1 coordinates');
assert(font.includes('result.pixels.resize_bytes(result.width * result.height)'), 'SDF atlas is not allocating an inferred byte buffer');
assert(font.includes('result.pixels.byte_data()'), 'SDF atlas is not exposing its byte buffer to FreeType');
assert(glmRaw.includes('extern "LSXMath.dll" fn _lsxGLMMat4PerspectiveRHNO'), 'raw GLM projection bridge missing');
assert(glm.includes('export const Vec2'), 'wrapped GLM Vec2 missing');
assert(glm.includes('export const Vec3'), 'wrapped GLM Vec3 missing');
assert(glm.includes('export const Vec4'), 'wrapped GLM Vec4 missing');
assert(glm.includes('export const Mat2'), 'wrapped GLM Mat2 missing');
assert(glm.includes('export const Mat3'), 'wrapped GLM Mat3 missing');
assert(glm.includes('export const Mat4'), 'wrapped GLM Mat4 missing');
assert(glm.includes('export const Quat'), 'wrapped GLM quaternion missing');
assert(glm.includes('export const DualQuat'), 'wrapped GLM dual quaternion missing');
assert(glm.includes('export fn decompose'), 'wrapped GLM decomposition missing');
assert(glm.includes('export fn pick_matrix'), 'wrapped GLM pick matrix missing');
assert(glm.includes('faceforward = fn'), 'wrapped GLM faceforward operations missing');
assert(glm.includes('rotate_vec4 = fn'), 'wrapped quaternion Vec4 rotation missing');
assert(!glm.includes('-> ptr'), 'public GLM wrapper must not expose native pointers');
assert(!glm.includes('export extern'), 'public GLM wrapper must not expose raw extern declarations');
assert(cameraMath.includes('export const Camera'), 'typed GLM camera object missing');
assert(cameraMath.includes('view_projection = fn'), 'camera view-projection helper missing');
assert(glmOpenGL.includes('export fn uniform_mat4'), 'GLM OpenGL matrix upload helper missing');
assert(compiler.includes("['lsxmath.dll', ['@LazyScript/native/LSXMath.dll']]"), 'LSXMath runtime staging rule missing');
assert(fs.existsSync(path.join(lazy, 'native', 'stb_image.dll')), 'stb_image native runtime missing');
assert(fs.existsSync(path.join(lazy, 'native', 'libfreetype.dll')), 'FreeType native runtime missing');
assert(fs.existsSync(path.join(lazy, 'native', 'LSXFreeType.dll')), 'FreeType LSX ABI bridge missing');
assert(fs.existsSync(path.join(lazy, 'native', 'LSXGLABI.dll')), 'exact OpenGL ABI bridge missing');
assert(fs.existsSync(path.join(lazy, 'native', 'LSXMath.dll')), 'GLM native runtime missing');

const fileExample = fs.readFileSync(path.join(toolkit, 'Projects', '21_file_io', 'main.lsx'), 'utf8');
assert(!fileExample.includes('"build/file_io_test.txt"'), 'file example must not write into build/build when run from the build directory');
assert(fileExample.includes('console.wait()'), 'file example must keep its console visible');
assert(fileExample.includes('Log.open_default()'), 'file example must leave persistent stage logs');
const jsonExample = fs.readFileSync(path.join(toolkit, 'Projects', '22_json', 'main.lsx'), 'utf8');
assert(jsonExample.includes('Log.open_default()'), 'JSON example must leave persistent stage logs');
assert(jsonExample.includes('console.wait()'), 'JSON example must keep its console visible');
assert(json.includes('source = {}'), 'JSON document must own inferred native source storage');

const examples = fs.readdirSync(path.join(toolkit, 'Projects'), { withFileTypes: true })
  .filter(e => e.isDirectory()).map(e => path.join(toolkit, 'Projects', e.name, 'main.lsx')).filter(fs.existsSync);
for (const file of examples) {
  const source = fs.readFileSync(file, 'utf8');
  assert(!/\bmemory\./.test(source), `${file} still exposes raw memory operations in project code`);
}

const allLsxFiles = [];
function collectLsx(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'build') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) collectLsx(full);
    else if (entry.isFile() && entry.name.endsWith('.lsx')) allLsxFiles.push(full);
  }
}
collectLsx(lazy);
collectLsx(path.join(toolkit, 'Projects'));
for (const file of allLsxFiles) {
  const source = fs.readFileSync(file, 'utf8');
  assert(!/\btable\s*</.test(source), `${file} still exposes typed collection syntax`);
}

const imageExample = fs.readFileSync(path.join(toolkit, 'Projects', '24_image_loading', 'main.lsx'), 'utf8');
assert(imageExample.includes('Texture2D.load_ui("assets/loaded_texture.png")'), 'image example is not using the typed stb_image texture API');
assert(imageExample.includes('GL.glBindTexture(GL.GL_TEXTURE_2D,texture.id)'), 'image example is not binding the decoded texture like example 04');
assert(imageExample.includes('GL.glDrawArrays(GL.GL_TRIANGLE_STRIP,0,4)'), 'image example is not drawing the same quad path as example 04');
assert(imageExample.includes('-0.8,-0.8, 0.0,1.0'), 'image example bottom UV no longer matches example 04');
assert(imageExample.includes('-0.8, 0.8, 0.0,0.0'), 'image example top UV no longer matches example 04');
assert(!imageExample.includes('TextureUpload'), 'image example must not use the FreeType texture-upload helper');
assert(imageExample.includes('Log.open_default()'), 'image example must leave persistent stage logs');
assert(imageExample.includes('First textured image frame rendered'), 'image example must log its first successful rendered frame');
const glmExample = fs.readFileSync(path.join(toolkit, 'Projects', '27_glm_camera', 'main.lsx'), 'utf8');
assert(glmExample.includes('use "@LazyScript/bindings/Math/GLM.lsx" as GLM'), 'GLM camera example does not use the typed wrapper');
assert(glmExample.includes('use "@LazyScript/bindings/Math/Camera.lsx" as Camera'), 'GLM camera example does not use the typed camera');
assert(glmExample.includes('GLM.trs(position,rotation,scale)'), 'GLM camera example does not use wrapped TRS');
assert(glmExample.includes('GLMOpenGL.uniform_mat4'), 'GLM camera example does not use typed matrix uniforms');
const triangle = fs.readFileSync(path.join(toolkit, 'Projects', '02_opengl_triangle', 'main.lsx'), 'utf8');
assert(triangle.includes('local vertices = {'), 'triangle does not use packed positional LSX object data');
assert(triangle.includes('vertices.byte_length()'), 'triangle does not derive native payload size from the LSX object');
const audio = fs.readFileSync(path.join(toolkit, 'Projects', '08_openal_generated_tone', 'main.lsx'), 'utf8');
assert(audio.includes('local pcm = {}'), 'generated audio does not use an inferred LSX collection');
assert(!audio.includes('table<'), 'generated audio still exposes a typed collection annotation');
assert(!fs.existsSync(path.join(lazy, 'bindings', 'Platform', 'WICImage.lsx')), 'WIC should not be active');
const api = JSON.parse(fs.readFileSync(path.join(lazy, 'api', 'api-data.json'), 'utf8'));
assert(api.stats.total >= 9000, 'offline HTML API is incomplete');
assert(fs.existsSync(path.join(toolkit, 'LazyScriptEX-Native-GameKit-0.18.4.vsix')), 'VS Code VSIX missing');
assert(fs.existsSync(path.join(toolkit, 'INSTALL_VSCODE_EXTENSION.bat')), 'VS Code extension installer missing');
assert(api.stats.modules['System/Threading'] > 0, 'threading API is missing from offline docs');
assert(api.stats.modules['Network/Sockets'] > 0, 'socket API is missing from offline docs');
assert(api.stats.modules['Network/Http'] > 0, 'HTTP API is missing from offline docs');
assert(api.stats.modules['System/File'] > 0, 'file API is missing from offline docs');
assert(api.stats.modules['Data/Json'] > 0, 'JSON API is missing from offline docs');
assert(api.stats.modules['Graphics/STBImage'] > 0, 'stb_image API is missing from offline docs');
assert(api.stats.modules['Graphics/Image'] > 0, 'image API is missing from offline docs');
assert(api.stats.modules['Graphics/Texture2D'] > 0, 'texture API is missing from offline docs');
assert(api.stats.modules['OpenGL/TextureUpload'] > 0, 'exact texture upload API is missing from offline docs');
assert(api.stats.modules['Text/FreeTypeRaw'] > 0, 'raw FreeType API is missing from offline docs');
assert(api.stats.modules['Text/FreeType'] > 0, 'typed FreeType API is missing from offline docs');
assert(api.stats.modules['Text/Font'] > 0, 'font API is missing from offline docs');
assert(api.stats.modules['Math/GLM'] > 0, 'typed GLM API is missing from offline docs');
assert(api.stats.modules['Math/GLMRaw'] > 0, 'raw GLM bridge API is missing from offline docs');
assert(api.stats.modules['Math/Camera'] > 0, 'camera math API is missing from offline docs');
assert(api.stats.modules['Math/OpenGL'] > 0, 'GLM OpenGL API is missing from offline docs');
assert(api.stats.kinds.method > 150, 'object methods are missing from rich API metadata');
assert(api.entries.some((entry) => entry.description && entry.description.length > 10), 'API descriptions are missing');
console.log('GLM math and cameras, annotation-free inferred collections, strings, files, JSON, direct stb_image, OpenGL textures, direct FreeType SDF fonts, compiler-emitted atomics, real threading, automatic runtime staging, sockets, HTTP, native LSHTML/LSCSS LazyUI, and VS Code package checks passed.');
